//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Userr
    {
        public int id { get; set; }
        public string u_name { get; set; }
        public string u_surname { get; set; }
        public string u_phonenumber { get; set; }
        public string u_email { get; set; }
        public Nullable<System.DateTime> u_date { get; set; }
    }
}
