//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationTest2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShortInfo
    {
        public int id { get; set; }
        public string u_HairColour { get; set; }
        public string u_Height { get; set; }
        public string u_Weight { get; set; }
    }
}
