//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int id { get; set; }
        public string PostTitle { get; set; }
        public string PostShortInfo { get; set; }
        public string PostPhoto { get; set; }
        public string PostContent { get; set; }
        public System.DateTime PostDate { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<int> Author_Id { get; set; }
        public Nullable<int> Category_Id { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Category Category { get; set; }
    }
}
